version: 1.0.0.{build}-{branch}
image: Visual Studio 2017
before_build:
- ps: dotnet restore
build:
  verbosity: minimal
artifacts:
- path: Nexusat.AspNetCore\bin\Debug\netcoreapp2.0\Nexusat.AspNetCore.dll
  name: Nexusat.AspNetCore.dll
notifications:
- provider: Email
  to:
  - giovanni.costagliola@nexusat.it
  subject: AspNetCore Build
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
- provider: Webhook
  url: https://webhooks.gitter.im/e/12c6a617e943ebd87b79
  method: POST
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
- provider: Slack
  incoming_webhook: https://hooks.slack.com/services/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
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true

